// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	AddAccountBalanceByID(ctx context.Context, arg AddAccountBalanceByIDParams) (Account, error)
	AddEntry(ctx context.Context, arg AddEntryParams) (Entry, error)
	AddTransfer(ctx context.Context, arg AddTransferParams) (Transfer, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccountByID(ctx context.Context, id int64) (Account, error)
	DeleteEntryByID(ctx context.Context, id int64) (Entry, error)
	DeleteTransferByID(ctx context.Context, id int64) (Transfer, error)
	DeleteUserByEmail(ctx context.Context, email string) (User, error)
	DeleteUserByID(ctx context.Context, id int64) (User, error)
	GetAccountByID(ctx context.Context, id int64) (Account, error)
	GetAccountByUserID(ctx context.Context, userID int64) (Account, error)
	GetEntries(ctx context.Context) ([]Entry, error)
	GetEntriesByAccountID(ctx context.Context, accountID int64) ([]Entry, error)
	GetEntryByID(ctx context.Context, id int64) (Entry, error)
	GetListAccounts(ctx context.Context) ([]Account, error)
	GetListUsers(ctx context.Context) ([]User, error)
	GetTransferByID(ctx context.Context, id int64) (Transfer, error)
	GetTransfers(ctx context.Context) ([]Transfer, error)
	GetTransfersByAccountID(ctx context.Context, fromAccountID int64) ([]Transfer, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id int64) (User, error)
	SelectAccountForUpdate(ctx context.Context, id int64) (Account, error)
	SelectUserForUpdate(ctx context.Context, id int64) (User, error)
	UpdateAccountBalanceByID(ctx context.Context, arg UpdateAccountBalanceByIDParams) (Account, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
